### ISSUE TITLE
[DX] Frontend Compilation failed error on stopping spring boot

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#12930]
### Description of the bug

Everytime I stop my application via IDEA I get the following error printed: 

![image](https://user-images.githubusercontent.com/3968629/152497948-09753bc5-d67b-4e89-992c-d906d035281b.png)

This did not happen in 2.3.0.alpha2 or earlier. 

### Expected behavior

No error is printed if I stop the application server.

### Minimal reproducible example

Don't have time to create a new application just for that atm. If you can't reproduce it; just close this ticket

### Versions

- Vaadin / Flow version: 23.0.0.beta1
- Java version: 11
- OS version: Ubuntu
- Browser version (if applicable): Firefox
- Application Server (if applicable): Spring Boot 2.6.3 / Tomcat
- IDE (if applicable): IDEA

**Comment by Artur-** [comment]
Is this when launching the `Application` class or through a Maven goal?

**Comment by knoobie** [comment]
Through the maven goal `spring boot run`. Sorry forgot to mention it

**Comment by Artur-** [comment]
Most likely caused by 4429a8f83e32c426e60fab6fa9fd5a4cffaafd1c

We need to handle "compile error" and "webpack was terminated by us" in different ways
