### ISSUE TITLE
TS types for node not found

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#22536]
### Description of the bug

In certain configurations, the Vite build fails with not finding type definitions for node:
```
[ERROR] The build process encountered an error: Vite process exited with non-zero exit code.
Stderr: ’vite v7.1.9 building for production...
transforming...
target/plugins/vite-plugin-service-worker/index.ts(1,23): error TS2688: Cannot find type definition file for ‘node’.
target/plugins/vite-plugin-service-worker/index.ts(2,35): error TS2307: Cannot find module ‘node:path’ or its corresponding type declarations.
```

It seems to be related to excluding react but there is no definite test case for it

### Expected behavior

It compiles

### Minimal reproducible example

See above

### Versions

- Vaadin / Flow version: 25.0 beta2

**Comment by mstahv** [comment]
Without this line this project doesn't compile with 25.0.0-beta2
https://github.com/viritin/widgetset/commit/0c5c63c0cf068acecba6698ff4a8fdf2c3a6d834#diff-8d04401f1cc51365fe3e32f019cd720135ba920a1a7da7f19e9c9208478701fcL44

**Comment by tltv** [comment]
I could not reproduce this with [this](https://github.com/viritin/widgetset/commit/0c5c63c0cf068acecba6698ff4a8fdf2c3a6d834#diff-8d04401f1cc51365fe3e32f019cd720135ba920a1a7da7f19e9c9208478701fcL44). Do you still get the same error @mstahv?
