### ISSUE TITLE
flow 1.0/1.2/1.4 snapshots fail in safari 9

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#5164]
Console shows following error:
>“Type error: a.children[Symbol.iterator] is not a function. (In "a.children\[Symbol.iterator\]()"”

Looks like it's related to `for (var child of node.children) {` introduced in #5142

Console error
![image](https://user-images.githubusercontent.com/9820084/53646935-1557db00-3c45-11e9-8ec4-63f87c804fd4.png)

Linked transpiled source
![image](https://user-images.githubusercontent.com/9820084/53646980-2f91b900-3c45-11e9-8b3a-ebbceea5a1dd.png)

**Comment by web-padawan** [comment]
Yes, we should never use `for..of` loops, neither `async..await` as the transpiled code needs Symbol polyfill. That polyfill is included in `@webcomponents/webcomponentsjs` 2.x for Polymer 3 only.
