### ISSUE TITLE
Error in production build with Maven plugin 24.4.0.alpha15

### ISSUE THREAD

**Issue by stefanbrenner** [vaadin/flow#19000]
### Describe the bug

With the Maven plugin (24.4.0.alpha15) I get the following error on building the application with production mode
`error TS2353: Object literal may only specify known properties, and 'continue' does not exist in type 'PreventCommands'.`

`
Execution default of goal com.vaadin:vaadin-maven-plugin:24.4.0.alpha15:build-frontend failed: Vite process exited with non-zero exit code.
[ERROR] Stderr: 'vite v5.1.6 building for production...
[ERROR] transforming...
[ERROR] frontend/generated/flow/Flow.tsx(187,17): error TS2353: Object literal may only specify known properties, and 'continue' does not exist in type 'PreventCommands'.
`

This is the content of Flow.d.ts:30
```js
export interface PreventCommands {
    prevent: () => any;
}
```

and the failing call in Flow.tsx:184
```js
if (mountedContainer?.onBeforeLeave) {
          mountedContainer?.onBeforeLeave({pathname: event.detail.pathname, search: event.detail.search}, {
              prevent() {},
              continue() {
                  mountedContainer?.parentNode?.removeChild(mountedContainer);
                  mountedContainer = undefined;
                  navigation(event.detail.pathname, {replace: false});
              }
          }, router);
```

### Reproduction

```xml
<profiles>
    <profile>
        <id>production</id>
        <properties>
            <vaadin.productionMode>true</vaadin.productionMode>
        </properties>

        <build>
            <plugins>
                <plugin>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <goals>
                                <goal>build-frontend</goal>
                            </goals>
                            <phase>compile</phase>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </build>
    </profile>
</profiles>
```

mvn clean install -Pproduction

### System Info

OSX Sonoma 14.4 (23E214)
Vaadin 24.4.0.alpha15

**Comment by mshabarov** [comment]
@stefanbrenner Thanks for the issue!

This is an unexpected error, as `PreventCommands` has `continue` defined, see https://github.com/vaadin/flow/blob/e2555cadbd40c9847e35d7b0cdbcd07e7598222d/flow-client/src/main/frontend/Flow.ts#L51C1-L54C2.

Could you please try to delete `./frontend/generated` folder and re-run your app, so that all the files get generated again with a proper versions?

This sounds like version mismatch of `flow-server` and `flow-client` versions, as `continue` was added recently in 24.4.

**Comment by stefanbrenner** [comment]
Unfortunately this doesn't solve the problem.

I delete frontend/generated, node_mudules, package.json but nothing helped.

**Comment by mshabarov** [comment]
Could you please also check if `com.vaadi:flow-server`, `com.vaadin:flow-client` and `com.vaadin:vaadin-maven-plugin` have the same versions in the resolved Maven dependency tree?

**Comment by stefanbrenner** [comment]
Not the same but just a little difference:

com.vaadin:flow-server:jar:24.4.0.alpha9
com.vaadin:flow-client:jar:24.4.0.alpha9
com.vaadin:vaadin-maven-plugin:vaadin-24.4.0.alpha15

**Comment by mshabarov** [comment]
> com.vaadin:flow-server:jar:24.4.0.alpha9
com.vaadin:flow-client:jar:24.4.0.alpha9
com.vaadin:vaadin-maven-plugin:vaadin-24.4.0.alpha15

This doesn't seem correct. Vaadin Platform (and vaadin-maven-plugin) is build and should use Flow dependencies with version 24.4.0.alpha22, see https://github.com/vaadin/platform/releases/tag/24.4.0.alpha15.

Do you use `com.vaadin:vaadin` or `com.vaadin:vaadin-core`, or explicit versions of `flow-server` and `flow-client`? You'll probably need to build a dependency tree and check from where these old versions (24.4.0.alpha9) come from.

**Comment by stefanbrenner** [comment]
Not I solved the problem thanks to your help. I checked the whole dependency tree and found the wrong project configuration that finally caused the issue. Now the correct versions of all Vaadin dependencies are used.

Thank you so much for your support!
