### PR TITLE
Check the function presence before calling it

### LINKED ISSUE #5206: Vaadin 13: Text in ComponentRenderer results in TypeError
**Description of the bug:**
Since I updated to the final version of Vaadin 13, the `ComponentRenderer` throws an error, if I use a `Text` inside it.
The error is `TypeError: node.hasAttribute is not a function`, thrown in [flow-component-renderer#_isFocusable](https://github.com/vaadin/flow/blob/master/flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html#L168).
The reason for this error is probably, that the `Text`-component is no HTML-Element and therefor has no `hasAttribute` method.
My guess is, that the bug has been introduced with #5142.

**Minimal reproducible example**

1. Download the [Project-Base for Vaadin Flow](https://vaadin.com/start/latest/project-base)
2. In the `MainView` add a `Grid` and add a column, which uses a `ComponentRenderer` with `Text` to it.
Example: `grid.addColumn(new ComponentRenderer<>(item -> new Text(item.id))).setHeader("ID");`
3. Run the application.

**Expected behavior**
The `Grid` should render normally, without throwing an error
**Actual behavior**
An error is thrown and the `Grid` is not renderer properly.

**Version:**
- Vaadin 13.0.0

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #5206

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5208)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Test available here: https://github.com/vaadin/vaadin-grid-flow/pull/577
It fails currently and it doesn't fail with the PR (checked).
