### ISSUE TITLE
Vaadin 13: Text in ComponentRenderer results in TypeError

### ISSUE THREAD

**Issue by Springrbua** [vaadin/flow#5206]
**Description of the bug:**
Since I updated to the final version of Vaadin 13, the `ComponentRenderer` throws an error, if I use a `Text` inside it.
The error is `TypeError: node.hasAttribute is not a function`, thrown in [flow-component-renderer#_isFocusable](https://github.com/vaadin/flow/blob/master/flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html#L168).
The reason for this error is probably, that the `Text`-component is no HTML-Element and therefor has no `hasAttribute` method.
My guess is, that the bug has been introduced with #5142.

**Minimal reproducible example**

1. Download the [Project-Base for Vaadin Flow](https://vaadin.com/start/latest/project-base)
2. In the `MainView` add a `Grid` and add a column, which uses a `ComponentRenderer` with `Text` to it.
Example: `grid.addColumn(new ComponentRenderer<>(item -> new Text(item.id))).setHeader("ID");`
3. Run the application.

**Expected behavior**
The `Grid` should render normally, without throwing an error
**Actual behavior**
An error is thrown and the `Grid` is not renderer properly.

**Version:**
- Vaadin 13.0.0

**Comment by denis-anisimov** [comment]
Yes, it's a regression introduced by fix for #4191.
The code in fix should be aware of type of the node when calling functions.
