### ISSUE TITLE
------------------ Frontend compilation failed. ------------------ output when server is stopped

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12107]
### Description of the bug / feature
Whenever the server is stopped, it outputs
```
------------------ Frontend compilation failed. ------------------
```

Probably caused by #12089
