### ISSUE TITLE
demo-google-signin demo does not work with flow 0.1.9

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#1839]
Open 
http://flow.app.fi/demo-google-signin-0.1.9/
and press the only button it has.

Expected: something good is happening

Actual: nothing is happening, console has errors:

```
google-signin.html:1 Uncaught TypeError: this.$.aware.signIn is not a function
    at HTMLElement.signIn (google-signin.html:1)
    at HTMLDivElement.<anonymous> (template-stamp.html:1)
```
